apiVersion: v2
name: meilisearch
description: MeiliSearch deployment for PostPunk Archive
type: application
version: 1.8.0
appVersion: "v1.8.0"
home: https://meilisearch.com
sources:
  - https://github.com/meilisearch/meilisearch
keywords:
  - search
  - fulltext
  - database